tags:
- name: acronym
  description: acronyms API

paths:
# [GET] acronym
  /acronym:
    get:
      tags:
      - acronym
      summary: Find acronyms
      parameters:
      - name: from
        in: query
        type: integer
      - name: limit
        in: query
        type: integer
      - name: search
        in: query
        type: string

      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] acronym
    post:
      tags:
      - acronym
      summary: Add Acronym
      parameters:
      - in: body
        name: acronym
        description: acronym, definition
        required: true
        schema:
          type: object
          required:
            - acronym
            - definition
          properties:
            acronym:
              type: string
              description: abb
            definition:
              type: string
              description: long definition

      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  /acronym/{acronym}:
# [PUT] acronym/acronym
    put:
      tags:
      - acronym
      summary: Update acronym
      parameters:
      - name: acronym
        in: path
        description: acronym
        required: true
        type: string

      - name: definition
        in: body
        description: definition
        required: true
        schema:
          type: object
          required:
            -definition
          properties:
            definition:
              type: string
              description: long definition

      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] acronym/acronym
    delete:
      tags:
      - acronym
      summary: Delete Acronym
      parameters:
      - name: acronym
        in: path
        description: acronym
        required: true
        type: string
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  acronym:
    type: object
    required:
        - acronym
        - definition
    properties:
      acronym:
        type: string
        description: abb
      definition:
        type: string
        description: long definition

schemes:
 - https
 - http
